server:
  port: 8090
  
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: collegeModule
        uri: lb://college-service
        predicates:
        - Path=/college/**
      - id: courseModule
        uri: lb://course-service
        predicates:
        - Path=/course/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka          
          
